"""`ErrorCode` -- one flat, stable enum shared across the whole system.

Every domain contributes its own block of values (grouped below purely
for readability; the enum itself has no notion of "domain" as a
sub-structure) -- a stable, language- and framework-independent
identifier a Telegram bot, a future REST API, a mobile app, or an admin
panel can all switch on without depending on Python exception classes or
translated message text.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    # --- User ---------------------------------------------------------
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_BANNED = "USER_BANNED"
    USER_INACTIVE = "USER_INACTIVE"

    # --- Driver --------------------------------------------------------
    DRIVER_NOT_FOUND = "DRIVER_NOT_FOUND"
    DRIVER_ALREADY_EXISTS = "DRIVER_ALREADY_EXISTS"
    DRIVER_NOT_VERIFIED = "DRIVER_NOT_VERIFIED"
    DRIVER_ALREADY_VERIFIED = "DRIVER_ALREADY_VERIFIED"
    DRIVER_BANNED = "DRIVER_BANNED"

    # --- Passenger -------------------------------------------------------
    PASSENGER_NOT_FOUND = "PASSENGER_NOT_FOUND"
    PASSENGER_ALREADY_EXISTS = "PASSENGER_ALREADY_EXISTS"
    PASSENGER_BLOCKED = "PASSENGER_BLOCKED"

    # --- Vehicle ---------------------------------------------------------
    VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND"
    VEHICLE_ALREADY_EXISTS = "VEHICLE_ALREADY_EXISTS"
    VEHICLE_NOT_APPROVED = "VEHICLE_NOT_APPROVED"
    VEHICLE_ALREADY_VERIFIED = "VEHICLE_ALREADY_VERIFIED"
    VEHICLE_DOCUMENTS_INCOMPLETE = "VEHICLE_DOCUMENTS_INCOMPLETE"
    VEHICLE_INVALID_DATA = "VEHICLE_INVALID_DATA"
    VEHICLE_DOCUMENT_NOT_FOUND = "VEHICLE_DOCUMENT_NOT_FOUND"
    DRIVER_DOCUMENT_NOT_FOUND = "DRIVER_DOCUMENT_NOT_FOUND"
    INVALID_DOCUMENT_STATUS_TRANSITION = "INVALID_DOCUMENT_STATUS_TRANSITION"

    # --- Geography ---------------------------------------------------------
    GEOGRAPHY_NOT_FOUND = "GEOGRAPHY_NOT_FOUND"
    INVALID_HIERARCHY_LEVEL = "INVALID_HIERARCHY_LEVEL"
    DIRECTION_NOT_FOUND = "DIRECTION_NOT_FOUND"
    DIRECTION_ALREADY_EXISTS = "DIRECTION_ALREADY_EXISTS"
    DIRECTION_NOT_SUPPORTED = "DIRECTION_NOT_SUPPORTED"

    # --- Advertisement -----------------------------------------------------
    ADVERTISEMENT_NOT_FOUND = "ADVERTISEMENT_NOT_FOUND"
    ADVERTISEMENT_FULL = "ADVERTISEMENT_FULL"
    ADVERTISEMENT_EXPIRED = "ADVERTISEMENT_EXPIRED"
    ADVERTISEMENT_CLOSED = "ADVERTISEMENT_CLOSED"
    ADVERTISEMENT_CANCELLED = "ADVERTISEMENT_CANCELLED"
    ADVERTISEMENT_ALREADY_ACTIVE = "ADVERTISEMENT_ALREADY_ACTIVE"
    ADVERTISEMENT_INVALID_DATA = "ADVERTISEMENT_INVALID_DATA"
    ADVERTISEMENT_INVALID_STATUS_TRANSITION = "ADVERTISEMENT_INVALID_STATUS_TRANSITION"
    ADVERTISEMENT_INSUFFICIENT_SEATS = "ADVERTISEMENT_INSUFFICIENT_SEATS"
    ADVERTISEMENT_SEAT_LIMIT_EXCEEDED = "ADVERTISEMENT_SEAT_LIMIT_EXCEEDED"
    ADVERTISEMENT_VEHICLE_NOT_ELIGIBLE = "ADVERTISEMENT_VEHICLE_NOT_ELIGIBLE"
    ADVERTISEMENT_DRIVER_NOT_ELIGIBLE = "ADVERTISEMENT_DRIVER_NOT_ELIGIBLE"
    ADVERTISEMENT_DIRECTION_NOT_ELIGIBLE = "ADVERTISEMENT_DIRECTION_NOT_ELIGIBLE"

    # --- Booking -----------------------------------------------------------
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    BOOKING_ALREADY_EXISTS = "BOOKING_ALREADY_EXISTS"
    BOOKING_EXPIRED = "BOOKING_EXPIRED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"
    BOOKING_REJECTED = "BOOKING_REJECTED"
    BOOKING_INVALID_STATUS_TRANSITION = "BOOKING_INVALID_STATUS_TRANSITION"
    BOOKING_INVALID_DATA = "BOOKING_INVALID_DATA"
    BOOKING_INSUFFICIENT_SEATS = "BOOKING_INSUFFICIENT_SEATS"
    BOOKING_SELF_BOOKING = "BOOKING_SELF_BOOKING"
    BOOKING_ADVERTISEMENT_NOT_BOOKABLE = "BOOKING_ADVERTISEMENT_NOT_BOOKABLE"
    BOOKING_PASSENGER_NOT_ELIGIBLE = "BOOKING_PASSENGER_NOT_ELIGIBLE"

    # --- Trip ----------------------------------------------------------
    TRIP_NOT_FOUND = "TRIP_NOT_FOUND"
    TRIP_ALREADY_STARTED = "TRIP_ALREADY_STARTED"
    TRIP_COMPLETED = "TRIP_COMPLETED"
    TRIP_CANCELLED = "TRIP_CANCELLED"
    TRIP_ALREADY_EXISTS = "TRIP_ALREADY_EXISTS"
    TRIP_ADVERTISEMENT_NOT_ELIGIBLE = "TRIP_ADVERTISEMENT_NOT_ELIGIBLE"
    TRIP_DRIVER_NOT_ELIGIBLE = "TRIP_DRIVER_NOT_ELIGIBLE"
    TRIP_VEHICLE_NOT_ELIGIBLE = "TRIP_VEHICLE_NOT_ELIGIBLE"
    TRIP_BOOKING_NOT_ELIGIBLE = "TRIP_BOOKING_NOT_ELIGIBLE"
    TRIP_PASSENGER_NOT_ELIGIBLE = "TRIP_PASSENGER_NOT_ELIGIBLE"
    TRIP_NO_PASSENGERS = "TRIP_NO_PASSENGERS"
    TRIP_INVALID_STATUS_TRANSITION = "TRIP_INVALID_STATUS_TRANSITION"
    TRIP_PASSENGER_NOT_FOUND = "TRIP_PASSENGER_NOT_FOUND"
    TRIP_BOARDING_INVALID_TRANSITION = "TRIP_BOARDING_INVALID_TRANSITION"

    # --- Rating --------------------------------------------------------
    RATING_NOT_FOUND = "RATING_NOT_FOUND"
    RATING_ALREADY_EXISTS = "RATING_ALREADY_EXISTS"
    RATING_INVALID_DATA = "RATING_INVALID_DATA"
    RATING_SELF_RATING = "RATING_SELF_RATING"
    RATING_TRIP_NOT_ELIGIBLE = "RATING_TRIP_NOT_ELIGIBLE"
    RATING_BOOKING_NOT_FOUND = "RATING_BOOKING_NOT_FOUND"

    # --- Complaint -----------------------------------------------------
    COMPLAINT_NOT_FOUND = "COMPLAINT_NOT_FOUND"
    COMPLAINT_ALREADY_RESOLVED = "COMPLAINT_ALREADY_RESOLVED"
    COMPLAINT_INVALID_DATA = "COMPLAINT_INVALID_DATA"
    COMPLAINT_REFERENCE_NOT_FOUND = "COMPLAINT_REFERENCE_NOT_FOUND"
    COMPLAINT_DISMISSED = "COMPLAINT_DISMISSED"

    # --- Notification --------------------------------------------------
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    NOTIFICATION_DELIVERY_FAILED = "NOTIFICATION_DELIVERY_FAILED"

    # --- Authentication --------------------------------------------------
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    SESSION_EXPIRED = "SESSION_EXPIRED"

    # --- Permission ------------------------------------------------------
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"

    # --- Matching --------------------------------------------------------
    MATCHING_NOT_FOUND = "MATCHING_NOT_FOUND"
    NO_AVAILABLE_DRIVERS = "NO_AVAILABLE_DRIVERS"

    # --- Location (Geo Engine) --------------------------------------------
    LOCATION_NOT_SUPPORTED = "LOCATION_NOT_SUPPORTED"
    INVALID_COORDINATES = "INVALID_COORDINATES"
