"""initial schema

Revision ID: 456c700ca981
Revises:
Create Date: 2026-07-14 06:07:40.794670

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "456c700ca981"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrative_areas",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "COUNTRY",
                "REGION",
                "DISTRICT",
                "CITY",
                "TOWN",
                "VILLAGE",
                "MAHALLA",
                "STREET",
                name="administrativearealevel",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("id != parent_id", name=op.f("ck_administrative_areas_no_self_parent")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["administrative_areas.id"],
            name=op.f("fk_administrative_areas_parent_id_administrative_areas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_administrative_areas")),
    )
    op.create_index(
        "ix_administrative_areas_lat_lng",
        "administrative_areas",
        ["latitude", "longitude"],
        unique=False,
    )
    op.create_index(
        "ix_administrative_areas_level", "administrative_areas", ["level"], unique=False
    )
    op.create_index(
        "ix_administrative_areas_name_trgm",
        "administrative_areas",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_administrative_areas_parent_name",
        "administrative_areas",
        ["parent_id", "name"],
        unique=False,
    )
    op.create_index(
        "ix_administrative_areas_parent_sort",
        "administrative_areas",
        ["parent_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "PASSENGER",
                "DRIVER",
                "ADMIN",
                name="userrole",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(
        "uq_users_phone_number_active",
        "users",
        ["phone_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "admin_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "admin_role",
            sa.Enum(
                "SUPER_ADMIN",
                "MODERATOR",
                "SUPPORT",
                name="adminrole",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_admin_profiles_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_admin_profiles_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_admin_profiles_user_id")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "LOGIN",
                "LOGOUT",
                "APPROVE",
                "REJECT",
                "BOOK",
                "CANCEL",
                "START",
                "COMPLETE",
                name="auditaction",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_target_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_actor_user_id", "audit_logs", ["actor_user_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_entity_id", "audit_logs", ["entity_id"], unique=False)
    op.create_index("ix_audit_logs_entity_type", "audit_logs", ["entity_type"], unique=False)
    op.create_index("ix_audit_logs_target_user_id", "audit_logs", ["target_user_id"], unique=False)
    op.create_table(
        "directions",
        sa.Column("origin_area_id", sa.Uuid(), nullable=False),
        sa.Column("destination_area_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin_area_id != destination_area_id", name=op.f("ck_directions_no_self_direction")
        ),
        sa.ForeignKeyConstraint(
            ["destination_area_id"],
            ["administrative_areas.id"],
            name=op.f("fk_directions_destination_area_id_administrative_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["origin_area_id"],
            ["administrative_areas.id"],
            name=op.f("fk_directions_origin_area_id_administrative_areas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directions")),
        sa.UniqueConstraint(
            "origin_area_id", "destination_area_id", name=op.f("uq_directions_origin_area_id")
        ),
    )
    op.create_table(
        "driver_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "approval_status",
            sa.Enum(
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                name="driverapprovalstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "availability_status",
            sa.Enum(
                "ONLINE",
                "OFFLINE",
                "BUSY",
                "ON_TRIP",
                "BANNED",
                name="driveravailabilitystatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("ratings_count", sa.Integer(), nullable=False),
        sa.Column("completed_trips_count", sa.Integer(), nullable=False),
        sa.Column("cancelled_trips_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_driver_profiles_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_driver_profiles_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_driver_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_driver_profiles_user_id")),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "SYSTEM",
                "BOOKING",
                "ADVERTISEMENT",
                "TRIP",
                "PAYMENT",
                "SECURITY",
                "WARNING",
                "PROMOTION",
                name="notificationtype",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "TELEGRAM",
                "PUSH",
                "SMS",
                "EMAIL",
                name="notificationchannel",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "delivery_status",
            sa.Enum(
                "PENDING",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                name="notificationstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivered_at IS NULL OR sent_at IS NULL OR delivered_at >= sent_at",
            name=op.f("ck_notifications_delivered_after_sent"),
        ),
        sa.CheckConstraint(
            "failed_at IS NULL OR failed_at >= created_at",
            name=op.f("ck_notifications_failed_after_created"),
        ),
        sa.CheckConstraint(
            "read_at IS NULL OR delivered_at IS NULL OR read_at >= delivered_at",
            name=op.f("ck_notifications_read_after_delivered"),
        ),
        sa.CheckConstraint(
            "sent_at IS NULL OR sent_at >= created_at",
            name=op.f("ck_notifications_sent_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_channel", "notifications", ["channel"], unique=False)
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"], unique=False)
    op.create_index(
        "ix_notifications_delivery_status", "notifications", ["delivery_status"], unique=False
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_table(
        "passenger_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "passenger_status",
            sa.Enum(
                "ACTIVE",
                "WAITING",
                "BOOKED",
                "ON_TRIP",
                "COMPLETED",
                "BANNED",
                name="passengerstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("ratings_count", sa.Integer(), nullable=False),
        sa.Column("completed_trips_count", sa.Integer(), nullable=False),
        sa.Column("cancelled_bookings_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_passenger_profiles_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_passenger_profiles_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_passenger_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passenger_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_passenger_profiles_user_id")),
    )
    op.create_table(
        "driver_documents",
        sa.Column("driver_profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "LICENSE",
                "PROFILE_PHOTO",
                "PASSPORT",
                "ID_CARD",
                name="driverdocumenttype",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("document_number", sa.String(length=100), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                name="verificationstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("verified_by_admin_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "expiry_date IS NULL OR issue_date IS NULL OR expiry_date > issue_date",
            name=op.f("ck_driver_documents_expiry_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["driver_profile_id"],
            ["driver_profiles.id"],
            name=op.f("fk_driver_documents_driver_profile_id_driver_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_admin_id"],
            ["admin_profiles.id"],
            name=op.f("fk_driver_documents_verified_by_admin_id_admin_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_documents")),
    )
    op.create_index(
        "ix_driver_documents_driver_profile_id",
        "driver_documents",
        ["driver_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_driver_documents_expiry_date", "driver_documents", ["expiry_date"], unique=False
    )
    op.create_index(
        "ix_driver_documents_verification_status",
        "driver_documents",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "vehicles",
        sa.Column("driver_profile_id", sa.Uuid(), nullable=False),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("manufacture_year", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=False),
        sa.Column("plate_number", sa.String(length=20), nullable=False),
        sa.Column(
            "vehicle_class",
            sa.Enum(
                "ECONOMY",
                "COMFORT",
                "BUSINESS",
                "MINIVAN",
                name="vehicleclass",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column("luggage_capacity", sa.Integer(), nullable=True),
        sa.Column("air_conditioning", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                name="verificationstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("seat_count > 0", name=op.f("ck_vehicles_seat_count_positive")),
        sa.ForeignKeyConstraint(
            ["driver_profile_id"],
            ["driver_profiles.id"],
            name=op.f("fk_vehicles_driver_profile_id_driver_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(
        "ix_vehicles_driver_profile_id", "vehicles", ["driver_profile_id"], unique=False
    )
    op.create_index(
        "ix_vehicles_verification_status", "vehicles", ["verification_status"], unique=False
    )
    op.create_index("ix_vehicles_verified", "vehicles", ["verified"], unique=False)
    op.create_index(
        "uq_vehicles_plate_number_active",
        "vehicles",
        ["plate_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "advertisements",
        sa.Column("driver_profile_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_area_id", sa.Uuid(), nullable=False),
        sa.Column("destination_area_id", sa.Uuid(), nullable=False),
        sa.Column("current_latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("current_longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_arrival_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("reserved_seats", sa.Integer(), nullable=False),
        sa.Column("available_seats", sa.Integer(), nullable=False),
        sa.Column(
            "advertisement_status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "FULL",
                "CLOSED",
                "CANCELLED",
                "EXPIRED",
                name="advertisementstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_priority", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_seats + reserved_seats <= total_seats",
            name=op.f("ck_advertisements_seats_within_total"),
        ),
        sa.CheckConstraint(
            "available_seats <= total_seats",
            name=op.f("ck_advertisements_available_seats_within_total"),
        ),
        sa.CheckConstraint(
            "available_seats >= 0", name=op.f("ck_advertisements_available_seats_non_negative")
        ),
        sa.CheckConstraint(
            "departure_time < expires_at", name=op.f("ck_advertisements_departure_before_expiry")
        ),
        sa.CheckConstraint(
            "pickup_area_id != destination_area_id",
            name=op.f("ck_advertisements_pickup_destination_distinct"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_advertisements_price_non_negative")),
        sa.CheckConstraint(
            "reserved_seats <= total_seats",
            name=op.f("ck_advertisements_reserved_seats_within_total"),
        ),
        sa.CheckConstraint(
            "reserved_seats >= 0", name=op.f("ck_advertisements_reserved_seats_non_negative")
        ),
        sa.CheckConstraint("total_seats > 0", name=op.f("ck_advertisements_total_seats_positive")),
        sa.ForeignKeyConstraint(
            ["destination_area_id"],
            ["administrative_areas.id"],
            name=op.f("fk_advertisements_destination_area_id_administrative_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["directions.id"],
            name=op.f("fk_advertisements_direction_id_directions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["driver_profile_id"],
            ["driver_profiles.id"],
            name=op.f("fk_advertisements_driver_profile_id_driver_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pickup_area_id"],
            ["administrative_areas.id"],
            name=op.f("fk_advertisements_pickup_area_id_administrative_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_advertisements_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advertisements")),
    )
    op.create_index(
        "ix_advertisements_advertisement_status",
        "advertisements",
        ["advertisement_status"],
        unique=False,
    )
    op.create_index(
        "ix_advertisements_departure_time", "advertisements", ["departure_time"], unique=False
    )
    op.create_index(
        "ix_advertisements_direction_departure",
        "advertisements",
        ["direction_id", "departure_time"],
        unique=False,
    )
    op.create_index(
        "ix_advertisements_direction_id", "advertisements", ["direction_id"], unique=False
    )
    op.create_index(
        "ix_advertisements_direction_status",
        "advertisements",
        ["direction_id", "advertisement_status"],
        unique=False,
    )
    op.create_index(
        "ix_advertisements_driver_profile_id", "advertisements", ["driver_profile_id"], unique=False
    )
    op.create_index(
        "ix_advertisements_driver_status",
        "advertisements",
        ["driver_profile_id", "advertisement_status"],
        unique=False,
    )
    op.create_index("ix_advertisements_expires_at", "advertisements", ["expires_at"], unique=False)
    op.create_index(
        "ix_advertisements_priority_status",
        "advertisements",
        ["is_priority", "advertisement_status"],
        unique=False,
    )
    op.create_table(
        "vehicle_documents",
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "REGISTRATION",
                "INSURANCE",
                "TECHNICAL_INSPECTION",
                name="vehicledocumenttype",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("document_number", sa.String(length=100), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                name="verificationstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("verified_by_admin_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "expiry_date IS NULL OR issue_date IS NULL OR expiry_date > issue_date",
            name=op.f("ck_vehicle_documents_expiry_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_vehicle_documents_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_admin_id"],
            ["admin_profiles.id"],
            name=op.f("fk_vehicle_documents_verified_by_admin_id_admin_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_documents")),
    )
    op.create_index(
        "ix_vehicle_documents_expiry_date", "vehicle_documents", ["expiry_date"], unique=False
    )
    op.create_index(
        "ix_vehicle_documents_vehicle_id", "vehicle_documents", ["vehicle_id"], unique=False
    )
    op.create_index(
        "ix_vehicle_documents_verification_status",
        "vehicle_documents",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "vehicle_photos",
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum(
                "FRONT",
                "BACK",
                "LEFT",
                "RIGHT",
                "INTERIOR",
                name="vehiclephototype",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_vehicle_photos_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_photos")),
    )
    op.create_index("ix_vehicle_photos_vehicle_id", "vehicle_photos", ["vehicle_id"], unique=False)
    op.create_index("ix_vehicle_photos_verified", "vehicle_photos", ["verified"], unique=False)
    op.create_table(
        "advertisement_status_history",
        sa.Column("advertisement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "FULL",
                "CLOSED",
                "CANCELLED",
                "EXPIRED",
                name="advertisementstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "FULL",
                "CLOSED",
                "CANCELLED",
                "EXPIRED",
                name="advertisementstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advertisement_id"],
            ["advertisements.id"],
            name=op.f("fk_advertisement_status_history_advertisement_id_advertisements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_advertisement_status_history_changed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advertisement_status_history")),
    )
    op.create_index(
        "ix_advertisement_status_history_advertisement_changed",
        "advertisement_status_history",
        ["advertisement_id", "changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_advertisement_status_history_advertisement_id",
        "advertisement_status_history",
        ["advertisement_id"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("advertisement_id", sa.Uuid(), nullable=False),
        sa.Column("passenger_profile_id", sa.Uuid(), nullable=False),
        sa.Column("requested_seats", sa.Integer(), nullable=False),
        sa.Column(
            "booking_status",
            sa.Enum(
                "PENDING",
                "RESERVED",
                "ACCEPTED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                "COMPLETED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("passenger_comment", sa.Text(), nullable=True),
        sa.Column("driver_comment", sa.Text(), nullable=True),
        sa.Column("reserved_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accepted_at IS NULL OR accepted_at >= created_at",
            name=op.f("ck_bookings_accepted_after_created"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR accepted_at IS NULL OR completed_at >= accepted_at",
            name=op.f("ck_bookings_completed_after_accepted"),
        ),
        sa.CheckConstraint("requested_seats <= 10", name=op.f("ck_bookings_requested_seats_max")),
        sa.CheckConstraint(
            "requested_seats > 0", name=op.f("ck_bookings_requested_seats_positive")
        ),
        sa.CheckConstraint(
            "reserved_until IS NULL OR reserved_until >= created_at",
            name=op.f("ck_bookings_reserved_until_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["advertisement_id"],
            ["advertisements.id"],
            name=op.f("fk_bookings_advertisement_id_advertisements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_profile_id"],
            ["passenger_profiles.id"],
            name=op.f("fk_bookings_passenger_profile_id_passenger_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_index("ix_bookings_advertisement_id", "bookings", ["advertisement_id"], unique=False)
    op.create_index(
        "ix_bookings_advertisement_status",
        "bookings",
        ["advertisement_id", "booking_status"],
        unique=False,
    )
    op.create_index("ix_bookings_booking_status", "bookings", ["booking_status"], unique=False)
    op.create_index(
        "ix_bookings_passenger_profile_id", "bookings", ["passenger_profile_id"], unique=False
    )
    op.create_index(
        "ix_bookings_passenger_status",
        "bookings",
        ["passenger_profile_id", "booking_status"],
        unique=False,
    )
    op.create_index("ix_bookings_reserved_until", "bookings", ["reserved_until"], unique=False)
    op.create_index(
        "ix_bookings_reserved_until_status",
        "bookings",
        ["reserved_until", "booking_status"],
        unique=False,
    )
    op.create_index(
        "uq_bookings_passenger_advertisement_active",
        "bookings",
        ["passenger_profile_id", "advertisement_id"],
        unique=True,
        postgresql_where=sa.text("booking_status IN ('PENDING', 'RESERVED', 'ACCEPTED')"),
    )
    op.create_table(
        "trips",
        sa.Column("advertisement_id", sa.Uuid(), nullable=False),
        sa.Column("driver_profile_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "trip_status",
            sa.Enum(
                "SCHEDULED",
                "READY",
                "STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="tripstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("start_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("start_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("end_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("end_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("total_distance_km", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(end_latitude IS NULL) = (end_longitude IS NULL)",
            name=op.f("ck_trips_end_coordinates_paired"),
        ),
        sa.CheckConstraint(
            "(start_latitude IS NULL) = (start_longitude IS NULL)",
            name=op.f("ck_trips_start_coordinates_paired"),
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes >= 0",
            name=op.f("ck_trips_duration_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_trips_ended_after_started"),
        ),
        sa.CheckConstraint(
            "total_distance_km IS NULL OR total_distance_km >= 0",
            name=op.f("ck_trips_total_distance_km_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["advertisement_id"],
            ["advertisements.id"],
            name=op.f("fk_trips_advertisement_id_advertisements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["driver_profile_id"],
            ["driver_profiles.id"],
            name=op.f("fk_trips_driver_profile_id_driver_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_trips_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
        sa.UniqueConstraint("advertisement_id", name=op.f("uq_trips_advertisement_id")),
    )
    op.create_index("ix_trips_advertisement_id", "trips", ["advertisement_id"], unique=False)
    op.create_index(
        "ix_trips_advertisement_status", "trips", ["advertisement_id", "trip_status"], unique=False
    )
    op.create_index("ix_trips_driver_profile_id", "trips", ["driver_profile_id"], unique=False)
    op.create_index(
        "ix_trips_driver_status", "trips", ["driver_profile_id", "trip_status"], unique=False
    )
    op.create_index("ix_trips_ended_at", "trips", ["ended_at"], unique=False)
    op.create_index("ix_trips_started_at", "trips", ["started_at"], unique=False)
    op.create_index("ix_trips_trip_status", "trips", ["trip_status"], unique=False)
    op.create_index("ix_trips_vehicle_id", "trips", ["vehicle_id"], unique=False)
    op.create_table(
        "booking_status_history",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "PENDING",
                "RESERVED",
                "ACCEPTED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                "COMPLETED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "PENDING",
                "RESERVED",
                "ACCEPTED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                "COMPLETED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_status_history_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_booking_status_history_changed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_status_history")),
    )
    op.create_index(
        "ix_booking_status_history_booking_changed",
        "booking_status_history",
        ["booking_id", "changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_booking_status_history_booking_id",
        "booking_status_history",
        ["booking_id"],
        unique=False,
    )
    op.create_table(
        "complaints",
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column(
            "complaint_type",
            sa.Enum(
                "DRIVER_MISCONDUCT",
                "PASSENGER_MISCONDUCT",
                "VEHICLE_CONDITION",
                "SAFETY_CONCERN",
                "PAYMENT_DISPUTE",
                "NO_SHOW",
                "OTHER",
                name="complaintreason",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.String(length=500), nullable=True),
        sa.Column(
            "complaint_status",
            sa.Enum(
                "OPEN",
                "UNDER_REVIEW",
                "RESOLVED",
                "DISMISSED",
                name="complaintstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "resolution_action",
            sa.Enum(
                "NONE",
                "WARNING",
                "BAN",
                name="complaintresolutionaction",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("resolved_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trip_id IS NOT NULL OR booking_id IS NOT NULL",
            name=op.f("ck_complaints_has_trip_or_booking"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_complaints_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_complaints_reporter_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_admin_id"],
            ["admin_profiles.id"],
            name=op.f("fk_complaints_resolved_by_admin_id_admin_profiles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_complaints_target_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_complaints_trip_id_trips"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
    )
    op.create_index("ix_complaints_booking_id", "complaints", ["booking_id"], unique=False)
    op.create_index(
        "ix_complaints_complaint_status", "complaints", ["complaint_status"], unique=False
    )
    op.create_index("ix_complaints_created_at", "complaints", ["created_at"], unique=False)
    op.create_index(
        "ix_complaints_reporter_user_id", "complaints", ["reporter_user_id"], unique=False
    )
    op.create_index(
        "ix_complaints_resolved_by_admin_id", "complaints", ["resolved_by_admin_id"], unique=False
    )
    op.create_index("ix_complaints_target_user_id", "complaints", ["target_user_id"], unique=False)
    op.create_index("ix_complaints_trip_id", "complaints", ["trip_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("driver_profile_id", sa.Uuid(), nullable=False),
        sa.Column("passenger_profile_id", sa.Uuid(), nullable=False),
        sa.Column("rater_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rater_role",
            sa.Enum(
                "PASSENGER",
                "DRIVER",
                name="partyrole",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("score >= 1 AND score <= 5", name=op.f("ck_ratings_score_within_range")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_ratings_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["driver_profile_id"],
            ["driver_profiles.id"],
            name=op.f("fk_ratings_driver_profile_id_driver_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_profile_id"],
            ["passenger_profiles.id"],
            name=op.f("fk_ratings_passenger_profile_id_passenger_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rater_user_id"],
            ["users.id"],
            name=op.f("fk_ratings_rater_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_ratings_target_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_ratings_trip_id_trips"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
        sa.UniqueConstraint("booking_id", "rater_role", name=op.f("uq_ratings_booking_id")),
    )
    op.create_index("ix_ratings_booking_id", "ratings", ["booking_id"], unique=False)
    op.create_index("ix_ratings_created_at", "ratings", ["created_at"], unique=False)
    op.create_index("ix_ratings_driver_profile_id", "ratings", ["driver_profile_id"], unique=False)
    op.create_index(
        "ix_ratings_passenger_profile_id", "ratings", ["passenger_profile_id"], unique=False
    )
    op.create_index("ix_ratings_rater_user_id", "ratings", ["rater_user_id"], unique=False)
    op.create_index("ix_ratings_score", "ratings", ["score"], unique=False)
    op.create_index("ix_ratings_target_user_id", "ratings", ["target_user_id"], unique=False)
    op.create_index("ix_ratings_trip_id", "ratings", ["trip_id"], unique=False)
    op.create_table(
        "trip_passengers",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("passenger_profile_id", sa.Uuid(), nullable=False),
        sa.Column("boarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dropped_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "boarding_status",
            sa.Enum(
                "WAITING",
                "BOARDED",
                "DROPPED_OFF",
                "NO_SHOW",
                name="boardingstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dropped_off_at IS NULL OR boarded_at IS NULL OR dropped_off_at >= boarded_at",
            name=op.f("ck_trip_passengers_dropped_off_after_boarded"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_trip_passengers_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_profile_id"],
            ["passenger_profiles.id"],
            name=op.f("fk_trip_passengers_passenger_profile_id_passenger_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_passengers_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_passengers")),
        sa.UniqueConstraint("trip_id", "booking_id", name=op.f("uq_trip_passengers_trip_id")),
    )
    op.create_index(
        "ix_trip_passengers_boarding_status", "trip_passengers", ["boarding_status"], unique=False
    )
    op.create_index(
        "ix_trip_passengers_booking_id", "trip_passengers", ["booking_id"], unique=False
    )
    op.create_index(
        "ix_trip_passengers_passenger_profile_id",
        "trip_passengers",
        ["passenger_profile_id"],
        unique=False,
    )
    op.create_index("ix_trip_passengers_trip_id", "trip_passengers", ["trip_id"], unique=False)
    op.create_table(
        "trip_status_history",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "SCHEDULED",
                "READY",
                "STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="tripstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "SCHEDULED",
                "READY",
                "STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="tripstatus",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_trip_status_history_changed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_status_history_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_status_history")),
    )
    op.create_index(
        "ix_trip_status_history_trip_changed",
        "trip_status_history",
        ["trip_id", "changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_trip_status_history_trip_id", "trip_status_history", ["trip_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trip_status_history_trip_id", table_name="trip_status_history")
    op.drop_index("ix_trip_status_history_trip_changed", table_name="trip_status_history")
    op.drop_table("trip_status_history")
    op.drop_index("ix_trip_passengers_trip_id", table_name="trip_passengers")
    op.drop_index("ix_trip_passengers_passenger_profile_id", table_name="trip_passengers")
    op.drop_index("ix_trip_passengers_booking_id", table_name="trip_passengers")
    op.drop_index("ix_trip_passengers_boarding_status", table_name="trip_passengers")
    op.drop_table("trip_passengers")
    op.drop_index("ix_ratings_trip_id", table_name="ratings")
    op.drop_index("ix_ratings_target_user_id", table_name="ratings")
    op.drop_index("ix_ratings_score", table_name="ratings")
    op.drop_index("ix_ratings_rater_user_id", table_name="ratings")
    op.drop_index("ix_ratings_passenger_profile_id", table_name="ratings")
    op.drop_index("ix_ratings_driver_profile_id", table_name="ratings")
    op.drop_index("ix_ratings_created_at", table_name="ratings")
    op.drop_index("ix_ratings_booking_id", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index("ix_complaints_trip_id", table_name="complaints")
    op.drop_index("ix_complaints_target_user_id", table_name="complaints")
    op.drop_index("ix_complaints_resolved_by_admin_id", table_name="complaints")
    op.drop_index("ix_complaints_reporter_user_id", table_name="complaints")
    op.drop_index("ix_complaints_created_at", table_name="complaints")
    op.drop_index("ix_complaints_complaint_status", table_name="complaints")
    op.drop_index("ix_complaints_booking_id", table_name="complaints")
    op.drop_table("complaints")
    op.drop_index("ix_booking_status_history_booking_id", table_name="booking_status_history")
    op.drop_index("ix_booking_status_history_booking_changed", table_name="booking_status_history")
    op.drop_table("booking_status_history")
    op.drop_index("ix_trips_vehicle_id", table_name="trips")
    op.drop_index("ix_trips_trip_status", table_name="trips")
    op.drop_index("ix_trips_started_at", table_name="trips")
    op.drop_index("ix_trips_ended_at", table_name="trips")
    op.drop_index("ix_trips_driver_status", table_name="trips")
    op.drop_index("ix_trips_driver_profile_id", table_name="trips")
    op.drop_index("ix_trips_advertisement_status", table_name="trips")
    op.drop_index("ix_trips_advertisement_id", table_name="trips")
    op.drop_table("trips")
    op.drop_index(
        "uq_bookings_passenger_advertisement_active",
        table_name="bookings",
        postgresql_where=sa.text("booking_status IN ('PENDING', 'RESERVED', 'ACCEPTED')"),
    )
    op.drop_index("ix_bookings_reserved_until_status", table_name="bookings")
    op.drop_index("ix_bookings_reserved_until", table_name="bookings")
    op.drop_index("ix_bookings_passenger_status", table_name="bookings")
    op.drop_index("ix_bookings_passenger_profile_id", table_name="bookings")
    op.drop_index("ix_bookings_booking_status", table_name="bookings")
    op.drop_index("ix_bookings_advertisement_status", table_name="bookings")
    op.drop_index("ix_bookings_advertisement_id", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(
        "ix_advertisement_status_history_advertisement_id",
        table_name="advertisement_status_history",
    )
    op.drop_index(
        "ix_advertisement_status_history_advertisement_changed",
        table_name="advertisement_status_history",
    )
    op.drop_table("advertisement_status_history")
    op.drop_index("ix_vehicle_photos_verified", table_name="vehicle_photos")
    op.drop_index("ix_vehicle_photos_vehicle_id", table_name="vehicle_photos")
    op.drop_table("vehicle_photos")
    op.drop_index("ix_vehicle_documents_verification_status", table_name="vehicle_documents")
    op.drop_index("ix_vehicle_documents_vehicle_id", table_name="vehicle_documents")
    op.drop_index("ix_vehicle_documents_expiry_date", table_name="vehicle_documents")
    op.drop_table("vehicle_documents")
    op.drop_index("ix_advertisements_priority_status", table_name="advertisements")
    op.drop_index("ix_advertisements_expires_at", table_name="advertisements")
    op.drop_index("ix_advertisements_driver_status", table_name="advertisements")
    op.drop_index("ix_advertisements_driver_profile_id", table_name="advertisements")
    op.drop_index("ix_advertisements_direction_status", table_name="advertisements")
    op.drop_index("ix_advertisements_direction_id", table_name="advertisements")
    op.drop_index("ix_advertisements_direction_departure", table_name="advertisements")
    op.drop_index("ix_advertisements_departure_time", table_name="advertisements")
    op.drop_index("ix_advertisements_advertisement_status", table_name="advertisements")
    op.drop_table("advertisements")
    op.drop_index(
        "uq_vehicles_plate_number_active",
        table_name="vehicles",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_vehicles_verified", table_name="vehicles")
    op.drop_index("ix_vehicles_verification_status", table_name="vehicles")
    op.drop_index("ix_vehicles_driver_profile_id", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_driver_documents_verification_status", table_name="driver_documents")
    op.drop_index("ix_driver_documents_expiry_date", table_name="driver_documents")
    op.drop_index("ix_driver_documents_driver_profile_id", table_name="driver_documents")
    op.drop_table("driver_documents")
    op.drop_table("passenger_profiles")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_notifications_delivery_status", table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_index("ix_notifications_channel", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("driver_profiles")
    op.drop_table("directions")
    op.drop_index("ix_audit_logs_target_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_type", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("admin_profiles")
    op.drop_index(
        "uq_users_phone_number_active",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("users")
    op.drop_index("ix_administrative_areas_parent_sort", table_name="administrative_areas")
    op.drop_index("ix_administrative_areas_parent_name", table_name="administrative_areas")
    op.drop_index(
        "ix_administrative_areas_name_trgm",
        table_name="administrative_areas",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("ix_administrative_areas_level", table_name="administrative_areas")
    op.drop_index("ix_administrative_areas_lat_lng", table_name="administrative_areas")
    op.drop_table("administrative_areas")
    # ### end Alembic commands ###
